version: '3.8'

services:
  simulator:
    build: .
    container_name: simulator
    environment:
      - INPUT_PARQUET_PATH=/app/data/flights.parquets   # Set the path to the Parquet file inside the container
      - OUTPUT_TYPE=terminal                            # Set the output type to terminal
      # - SPEEDUP_FACTOR=100000                           # Set the speedup factor to 100000
      - MAX_RECORDS=50                                  # Set the maximum number of records to process to 50
    volumes:
      # Map the local data directory to the /app/data directory in the container
      - ./data:/app/data