# Base configuration for Flink TaskManager workers
x-taskmanager-base: &taskmanager-base
  image: apache/flink:2.2.1-java21
  depends_on:
    - jobmanager
  command: /bin/bash -c "ln -f -s /opt/flink/plugins/metrics-influx/*.jar /opt/flink/lib/ && /docker-entrypoint.sh taskmanager"
  volumes:
    - hadoop-shared:/usr/local/hadoop:ro
  environment:
    HADOOP_CLASSPATH: /usr/local/hadoop/etc/hadoop:/usr/local/hadoop/share/hadoop/common/lib/*:/usr/local/hadoop/share/hadoop/common/*:/usr/local/hadoop/share/hadoop/hdfs/*:/usr/local/hadoop/share/hadoop/hdfs/lib/*
    FLINK_PROPERTIES: |
      jobmanager.rpc.address: jobmanager
      taskmanager.numberOfTaskSlots: 2
      metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
      metrics.reporter.influxdb.host: influxdb.flight-analysis.local
      metrics.reporter.influxdb.port: 8086
      metrics.reporter.influxdb.db: ${INFLUXDB_METRICS_BUCKET}
      metrics.reporter.influxdb.username: ${INFLUXDB_USER}
      metrics.reporter.influxdb.password: ${INFLUXDB_TOKEN}
      metrics.latency.interval: 1000
      state.backend: rocksdb
      state.backend.incremental: true
  networks:
    - sae-net

# Base configuration for HDFS DataNode workers
x-hdfs-worker-base: &hdfs-worker-base
  image: matnar/hadoop:3.3.2
  user: root
  networks:
    - sae-net
  tty: true
  stdin_open: true
  volumes:
    - ./hadoop/config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro
    - ./hadoop/config/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro
  environment:
    - NODE_TYPE=worker
    - HDFS_NAMENODE_HOST=${HDFS_NAMENODE_HOST}
  command: >
    sh -c "/usr/local/hadoop/bin/hdfs datanode & wait"

services:

    # ---------------------------------------------------------
    # LAYER 1: INFRASTRUCTURE
    # ---------------------------------------------------------

    # HDFS NameNode
    hdfs-master:
      image: matnar/hadoop:3.3.2
      container_name: hdfs-master
      user: root
      hostname: hdfs-master
      networks:
        sae-net:
          aliases:
            - ${HDFS_NAMENODE_HOST}
      ports:
        - "${HDFS_WEB_UI_PORT}:9870"
        - "${HDFS_NAMENODE_PORT}:54310"
      volumes:
        - hadoop-shared:/usr/local/hadoop
        - ./hadoop/config/workers:/usr/local/hadoop/etc/hadoop/workers:ro
        - ./hadoop/config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro
        - ./hadoop/config/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro
      environment:
        - NODE_TYPE=master
      command: >
        sh -c "if [ ! -d /tmp/hadoop-root/dfs/name ]; then
          /usr/local/hadoop/bin/hdfs namenode -format -force;
        fi;
        /usr/local/hadoop/bin/hdfs namenode &
        echo '[INFO] Wait for NameNode to be ready...';
        until /usr/local/hadoop/bin/hdfs dfsadmin -safemode wait; do
          echo '[INFO] NameNode not ready yet, retrying in 2s...';
          sleep 2;
        done;
        echo '[INFO] NameNode ready! Creating checkpoint directory...';
        /usr/local/hadoop/bin/hdfs dfs -mkdir -p /flink/checkpoints;
        /usr/local/hadoop/bin/hdfs dfs -chmod -R 777 /flink/checkpoints;
        wait"
      tty: true
      stdin_open: true

    # HDFS DataNode 1
    hdfs-worker-1:
      <<: *hdfs-worker-base
      container_name: hdfs-worker-1
      hostname: hdfs-worker-1
      networks:
        sae-net:
          aliases:
            - hdfs-worker-1.flight-analysis.local
      volumes:
        - ./hadoop/config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro
        - ./hadoop/config/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro
      depends_on:
        - hdfs-master

    # HDFS DataNode 2
    hdfs-worker-2:
      <<: *hdfs-worker-base
      container_name: hdfs-worker-2
      hostname: hdfs-worker-2
      networks:
        sae-net:
          aliases:
            - hdfs-worker-2.flight-analysis.local
      volumes:
        - ./hadoop/config/core-site.xml:/usr/local/hadoop/etc/hadoop/core-site.xml:ro
        - ./hadoop/config/hdfs-site.xml:/usr/local/hadoop/etc/hadoop/hdfs-site.xml:ro
      depends_on:
        - hdfs-master

    kafka:
      image: apache/kafka:4.3.1-rc
      container_name: kafka
      ports:
        - "${KAFKA_PORT}:9094"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka.flight-analysis.local:9092,EXTERNAL://127.0.0.1:${KAFKA_PORT}'
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 1
      healthcheck:
        test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
        interval: 5s
        timeout: 10s
        retries: 5
      networks:
        sae-net:
          aliases:
            - kafka.flight-analysis.local

    init-kafka:
      image: apache/kafka:4.3.1-rc
      container_name: init-kafka
      depends_on:
        kafka:
          condition: service_healthy
      networks:
        - sae-net
      entrypoint: [ "/bin/sh", "-c" ]
      command:
        - |
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-stream --replication-factor 1 --partitions 6
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q1-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q2-1h-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q2-6h-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q2-global-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q3-1d-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q3-7d-results --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka.flight-analysis.local:9092 --create --if-not-exists --topic flights-q3-global-results --replication-factor 1 --partitions 1

    influxdb:
      image: influxdb:2.7
      container_name: influxdb
      ports:
        - "${INFLUXDB_PORT}:8086"
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASS}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_RESULTS_BUCKET}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
        - INFLUXDB_METRICS_BUCKET=${INFLUXDB_METRICS_BUCKET}
      volumes:
        - influxdb-data:/var/lib/influxdb2
        - ./influxdb/influx-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        sae-net:
          aliases:
            - influxdb.flight-analysis.local

    telegraf:
      image: telegraf:1.31
      container_name: telegraf
      restart: on-failure
      depends_on:
        kafka:
          condition: service_healthy
        influxdb:
          condition: service_healthy
      volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      environment:
        - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
        - INFLUXDB_ORG=${INFLUXDB_ORG}
        - INFLUXDB_RESULTS_BUCKET=${INFLUXDB_RESULTS_BUCKET}
      networks:
        - sae-net

    # ---------------------------------------------------------
    # LAYER 2: PROCESSING
    # ---------------------------------------------------------

    jobmanager:
      image: apache/flink:2.2.1-java21
      container_name: jobmanager
      ports:
        - "${FLINK_PORT}:8081"
      command: /bin/bash -c "ln -f -s /opt/flink/plugins/metrics-influx/*.jar /opt/flink/lib/ && /docker-entrypoint.sh jobmanager"
      volumes:
        - hadoop-shared:/usr/local/hadoop:ro
      environment:
        HADOOP_CLASSPATH: /usr/local/hadoop/etc/hadoop:/usr/local/hadoop/share/hadoop/common/lib/*:/usr/local/hadoop/share/hadoop/common/*:/usr/local/hadoop/share/hadoop/hdfs/*:/usr/local/hadoop/share/hadoop/hdfs/lib/*
        FLINK_PROPERTIES: |
          jobmanager.rpc.address: jobmanager
          metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
          metrics.reporter.influxdb.host: influxdb.flight-analysis.local
          metrics.reporter.influxdb.port: 8086
          metrics.reporter.influxdb.db: ${INFLUXDB_METRICS_BUCKET}
          metrics.reporter.influxdb.username: ${INFLUXDB_USER}
          metrics.reporter.influxdb.password: ${INFLUXDB_TOKEN}
          metrics.latency.interval: 1000
          state.backend: rocksdb
          state.backend.incremental: true
      networks:
        sae-net:
          aliases:
            - flink.flight-analysis.local

    taskmanager-1:
      <<: *taskmanager-base
      container_name: taskmanager-1

    taskmanager-2:
      <<: *taskmanager-base
      container_name: taskmanager-2

    taskmanager-3:
      <<: *taskmanager-base
      container_name: taskmanager-3

    # ---------------------------------------------------------
    # LAYER 3: VISUALIZATION
    # ---------------------------------------------------------

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "${GRAFANA_PORT}:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      volumes:
        - grafana-data:/var/lib/grafana
        - ./data/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - ./data/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./data/grafana/dashboards:/var/lib/grafana/dashboards
      networks:
        - sae-net

networks:
  sae-net:
    driver: bridge
    name: sae-net

volumes:
  influxdb-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${PWD}/data/influxdb

  redis-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: ${PWD}/data/redis

  grafana-data:
        # driver: local
        # driver_opts:
        #   type: none
        #   o: bind
        #   device: ${PWD}/data/grafana

  hadoop-shared:
        # driver: local
        # driver_opts:
        #   type: none
        #   o: bind
        #   device: ${PWD}/shared/hadoop