apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-v2
    access: proxy
    url: http://influxdb.flight-analysis.local:8086
    jsonData:
      version: Flux
      organization: sae-org
      defaultBucket: flights-data
    secureJsonData:
      token: $INFLUXDB_TOKEN
    version: 1
    editable: true
