apiVersion: 1

datasources:
  - name: InfluxDB Results
    type: influxdb
    uid: influxdb-results
    access: proxy
    url: http://influxdb.flight-analysis.local:8086
    jsonData:
      version: Flux
      organization: sae-org
      defaultBucket: flights-data
    secureJsonData:
      token: apiv3_5C0GLRl9n4gviNmyGc4wtlALsMEaP804VBIJlLvSvBjxDB0_1QHiC8B6_i8kxnkRryAnXW8f9uSn9HANm1_5cA
    version: 1
    editable: true

  - name: InfluxDB Metrics
    type: influxdb
    uid: influxdb-metrics
    access: proxy
    url: http://influxdb.flight-analysis.local:8086
    jsonData:
      version: Flux
      organization: sae-org
      defaultBucket: flink-metrics
    secureJsonData:
      token: apiv3_5C0GLRl9n4gviNmyGc4wtlALsMEaP804VBIJlLvSvBjxDB0_1QHiC8B6_i8kxnkRryAnXW8f9uSn9HANm1_5cA
    version: 1
    editable: true
