kafka:
  host: "kafka.flight-analysis.local"
  internalPort: 9092
  externalPort: 9094
  inputTopic: "flights-stream"
  sinkTopic: "flights-results"
  groupId: "flink-system-test-group"

flink:
  host: "flink.flight-analysis.local"
  port: 8081
