kafka:
  host: "kafka.flight-analysis.local"
  internalPort: 9092
  externalPort: 9094
  inputTopic: "flights-stream"
  sinkTopic: "flights-results"
  groupId: "flink-analysis-group"
  outputTopics:
    q1: "flights-q1-results"
    q2: "flights-q2-results"
    q3: "flights-q3-results"

flink:
  host: "flink.flight-analysis.local"
  port: 8081
