name: flight-analysis-flink-worker

services:
  taskmanager:
    image: apache/flink:2.2.1-java21
    container_name: taskmanager
    network_mode: host
    command: >
      /bin/bash -c "
      mkdir -p /opt/flink/plugins/s3-fs-hadoop &&
      wget -qO /opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-2.2.1.jar https://repo.maven.apache.org/maven2/org/apache/flink/flink-s3-fs-hadoop/2.2.1/flink-s3-fs-hadoop-2.2.1.jar &&
      ln -f -s /opt/flink/plugins/metrics-influx/*.jar /opt/flink/lib/ &&
      /docker-entrypoint.sh taskmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager.flight-analysis.local
        taskmanager.numberOfTaskSlots: 2
        metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
        metrics.reporter.influxdb.host: influxdb.flight-analysis.local
        metrics.reporter.influxdb.port: 8086
        metrics.reporter.influxdb.db: ${INFLUXDB_METRICS_BUCKET}
        metrics.reporter.influxdb.username: ${INFLUXDB_USER}
        metrics.reporter.influxdb.password: ${INFLUXDB_TOKEN}
        metrics.latency.interval: 1000
        taskmanager.bind-host: 0.0.0.0
        taskmanager.host: ${NODE_HOSTNAME}
        state.backend: hashmap
        state.backend.incremental: false
    restart: always
