[agent]
  interval = "5s"
  flush_interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb.flight-analysis.local:8086"]
  token = "$INFLUXDB_TOKEN"
  organization = "$INFLUXDB_ORG"
  bucket = "$INFLUXDB_RESULTS_BUCKET"
  [outputs.influxdb_v2.tagdrop]
      host = ["*"]

[[inputs.kafka_consumer]]
  brokers = ["kafka.flight-analysis.local:9092"]
  topics = ["flights-q1-results"]
  max_undelivered_messages = 1000
  data_format = "json"
  kafka_version = "3.4.0"
  name_override = "flights_q1_results"
  offset = "oldest"
  consumer_group = "telegraf_flights_q1"
  json_time_key = "window_end"
  json_time_format = "2006-01-02 15:04:05"
  json_timezone = "UTC"
  tag_keys = ["airline"]

[[processors.starlark]]
  name_override = "flights_q1_results"
  source = '''
load("time.star", "time")

def apply(metric):
    end_nanos = metric.time

    start_nanos = end_nanos - 3600000000000

    end_secs = end_nanos // 1000000000
    start_secs = start_nanos // 1000000000

    metric.fields["window_end"] = time.from_timestamp(end_secs).format("2006-01-02 15:04:05")
    metric.fields["window_start"] = time.from_timestamp(start_secs).format("2006-01-02 15:04:05")

    return metric
'''

[[inputs.kafka_consumer]]
  brokers = ["kafka.flight-analysis.local:9092"]
  topics = ["flights-q2-1h-results", "flights-q2-6h-results", "flights-q2-global-results"]
  max_undelivered_messages = 1000
  data_format = "json"
  kafka_version = "3.4.0"
  name_override = "flights_q2_results"
  offset = "oldest"
  consumer_group = "telegraf_flights_q2"
  json_time_key = "window_end"
  json_time_format = "unix_ms"
  tag_keys = ["origin_airport_id", "window_type"]
  [inputs.kafka_consumer.tags]
    pipeline = "flight-analysis"

[[inputs.kafka_consumer]]
  brokers = ["kafka.flight-analysis.local:9092"]
  topics = ["flights-q3-results"]
  max_undelivered_messages = 1000
  data_format = "json"
  kafka_version = "3.4.0"
  name_override = "flights_q3_results"
  offset = "oldest"
  consumer_group = "telegraf_flights_q3"
  json_time_key = "window_end"
  json_time_format = "unix_ms"
  tag_keys = ["airline", "window_type"]
  [inputs.kafka_consumer.tags]
    pipeline = "flight-analysis"
